webdjango/profiles/urls.py
from . import views
from django.urls import path , include 
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'profiles'


urlpatterns = [
    # path('accounts/', include('profiles.accounts.urls', namespace='accounts')),
    # path('profiles/<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    # path('profiles/<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    # path('profiles/<slug:profile_slug>/', views.profile, name="profile"),
    path('<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    path('<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    path('<slug:profile_slug>/', views.profile, name="profile"),
    path('', views.profiles, name="profiles"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webdjango/reviews/urls.py
# from django.urls import path, include
# from .import views
# app_name = "reviews"
# urlpatterns = [
#     url(r'^$',views.review_list,name='review_list'),
#     url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
#     url(r'^wine$', views.wine_list, name='wine_list'),
#     url(r'^wine/(?P<wine_id>[0-9]+)/$', views.wine_detail, name='wine_detail'),
#     url(r'^wine/(?P<wine_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
#     url(r'^review/user/(?P<username>\w+)/$',views.user_review_list,name='user_review_list'),
#     url(r'^review/user/$',views.user_review_list,name='user_review_list'),
#     url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
# ]
from django.urls import path
from . import views

app_name = "reviews"
urlpatterns = [
    path('', views.review_list, name='review_list'),
    path('review/<int:review_id>/', views.review_detail, name='review_detail'),
    path('wine/', views.wine_list, name='wine_list'),
    path('wine/<int:wine_id>/', views.wine_detail, name='wine_detail'),
    path('wine/<int:wine_id>/add_review/', views.add_review, name='add_review'),
    path('review/user/<str:username>/', views.user_review_list, name='user_review_list'),
    path('review/user/', views.user_review_list, name='user_review_list'),
    path('recommendation/', views.user_recommendation_list, name='user_recommendation_list'),
]

webdjango/shop/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('about/', views.about, name="about"),
    path('', include('django.contrib.auth.urls')),
    #path('oauth/', include('social_django.urls', namespace="social")),
    path('product_list_category/', views.product_list_category, name="list"),
    path('', views.index, name="index"),
    path('product_list', views.index, name='product_list'),
    path('search/', views.search_list, name='query'),
    #path('trending/', views.search_list, name ='query'),
    path('<slug:category_slug>/', views.product_list_category, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('cat/<slug:subcategory_slug>/', views.product_list_subcategory, name='product_list_by_subcategory'),
    
    path('reviewlist/', views.review_list, name='review_list'),
    path('review/<int:review_id>/', views.review_detail, name='review_detail'),
    path('product/', views.product_list, name='product_list'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review'),
    path('review/user/<str:username>/', views.user_review_list, name='user_review_list'),
    path('review/user/', views.user_review_list, name='user_review_list'),
    path('recommendation/', views.user_recommendation_list, name='user_recommendation_list'),
]

webdjango/webdjango/urls.py
# from django.conf.urls import url
# from django.contrib import admin
# from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
# from . import views

# urlpatterns = [
#     path('', views.index, name="mainpage"),
#     path('admin/', admin.site.urls),
#     path('shop/', include('shop.urls')),
#     path('blog/', include('blog.urls')),
#     path('about/', views.about, name="about"),
#     url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
#     path('profiles/', include('profiles.urls')),
#     path(r'markdownx/', include('markdownx.urls')),
#     path('order/', include('order.urls')),
#     path('tfidf/', include('tfidf.urls')),
#     path('matrixfactorization/', include('matrixfactorization.urls')),
# ]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name="mainpage"),
    path('admin/', admin.site.urls),
    #path('shop/', include('shop.urls')),
    #path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),  # Sửa thành path
    path('profiles/', include('profiles.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls'),name="order"),
    path('tfidf/', include(('tfidf.urls'), namespace='tfidf')),
    path('matrixfactorization/', include(('matrixfactorization.urls'),namespace='matrixfactorization')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webdjango/profiles/models.py
from Lib.enum import auto
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


#profile info

class Profile(models.Model):
    """Profile Model"""
    # pub_date = models.DateTimeField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(default='', max_length=50, blank=True)
    last_name = models.CharField(default='', max_length=100, blank=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    email_verify = models.EmailField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=12, blank=True, null=True)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(blank=True, upload_to='avatar')
    city = models.CharField(max_length=255, blank=True)
    district = models.CharField(max_length=255, blank=True)
    country_of_residence = models.CharField(max_length=255, blank=True)
    hobby = models.CharField(max_length=255, blank=True)
    slug = models.SlugField(unique=True)

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     if self.first_name or self.last_name:
    #         self.slug = slugify("{}-{}-{}".format(self.first_name.lower(),
    #                                               self.last_name.lower(), self.id))
    #     else:
    #         self.slug = slugify('profiles:profile {}'.format(self.id))
    #     super().save()

    def save(self, *args, **kwargs):
        if not self.slug:
            if self.first_name and self.last_name:
                self.slug = slugify("{}-{}-{}".format(self.first_name.lower(),
                                                      self.last_name.lower(), self.user.username))
            else:
                self.slug = slugify('profiles:profile-{}'.format(self.user.username))
        super().save(*args, **kwargs)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('profiles:profile', args=[str(self.slug)])

    def display_bio(self):
        return mark_safe(self.bio)

webdjango/profiles/forms.py
from django.forms import ModelForm, Textarea

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from markdownx.fields import MarkdownxFormField
from django import forms
from .models import Profile
from django.core.validators import MinLengthValidator
from PIL import Image

app_name = 'profiles'

class ProfileForm(forms.ModelForm):
    """Profile Form + Fields for Photo Processing"""
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    bio = MarkdownxFormField(validators=[MinLengthValidator(10)])

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'email_verify',
            'date_of_birth',
            'bio',
            'city',
            'district',
            'country_of_residence',
            'hobby',
            'avatar',
            'x',
            'y',
            'width',
            'height',
        ]
        widgets = {
            # default date-format %m/%d/%Y will be used
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
        }

    def clean(self):
        """Clean the whole form"""
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('email_verify')

        if email != verify:
            raise forms.ValidationError('Emails do not match')

    def save(self):
        """Override the Save method for saving the crop photo"""
        photo = super().save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x is not None:
            image = Image.open(photo.avatar)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.avatar.path)
        return photo


class CustomChangePasswordForm(PasswordChangeForm):
    """Extending Password Change Form
    Overriding help_text

    """
    new_password1 = PasswordField()
    new_password2 = PasswordConfirmationField(confirm_with="new_password1")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        help_text = "<ul>" \
                    "<li>Your password can't be too similar to " \
                    "your other personal information</li>" \
                    "<li>Your password must contain " \
                    "at least 14 characters</li>" \
                    "<li>Your password can't be a " \
                    "commonly used password</li>" \
                    "<li>Your password can't be " \
                    "entirely numeric</li>" \
                    "<li>Your password must not be " \
                    "the same as the current password</li>" \
                    "<li>Your password must use of " \
                    "both uppercase and lowercase letters</li>" \
                    "<li>Your password must include " \
                    "of one or more numerical digits</li>" \
                    "<li>Your password must include " \
                    "of special characters, such as @, #, $</li>" \
                    "</ul>"
        self.fields['new_password1'].help_text = help_text

    class Meta:
        fields = [
            'old_password',
            'new_password1',
            'new_password2',
        ]

    def clean(self):
        """Clean is first in order not to have not matched
        error if other validation fails
        """
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 != new_password2:
            raise forms.ValidationError('Your new password and '
                                        'confirmation do not match')

    def clean_new_password1(self):
        """Validating the Password1 Field"""
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if check_password(new_password1, self.user.password):
            raise forms.ValidationError('Your password must not be '
                                        'the same as the current password')

        characters = set(new_password1)

        lower = any(letter.islower() for letter in characters)
        upper = any(letter.isupper() for letter in characters)
        digit = any(letter.isdigit() for letter in characters)

        if not upper:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not lower:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not digit:
            raise forms.ValidationError('Your password must include '
                                        'of one or more numerical digits')

        special_characters = ["@", "#", "$"]
        check = False
        for character in special_characters:
            if character in new_password1:
                check = True

        if not check:
            raise forms.ValidationError('Your password must include of '
                                        'special characters, such as @, #, $')

        first_name = self.user.profile.first_name.lower()
        last_name = self.user.profile.last_name.lower()

        if first_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        if last_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        return new_password1

webdjango/profiles/views.py
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, login_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from shop.models import Product
from .forms import ProfileForm, CustomChangePasswordForm
from .models import Profile


def profiles(request):
    """Load Homepage via Profile Link"""
    profiles = Profile.objects.all().filter(user_id=request.user.id)
    product_list = Product.objects.order_by('-name')
    return render(request, 'profilesindex.html', {'profiles': profiles,'product_list': product_list},)


@login_required
def profile(request, profile_slug):
    """Load Profile"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    return render(request, 'profile.html', {'profile': profile})


@login_required
def edit_profile(request, profile_slug):
    """Edit Profile Form"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "{} {}'s profile updated."
                             .format(form.cleaned_data["first_name"],
                                     form.cleaned_data["last_name"]))
            return HttpResponseRedirect(profile.get_absolute_url())
    return render(request, "edit-profile.html", {'form': form})


@login_required
def change_password(request, profile_slug):
    """Change Password Form"""
    if request.method == 'POST':
        form = CustomChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was '
                                      'successfully updated!')
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomChangePasswordForm(request.user)
    return render(request, 'change-password.html', {
        'form': form
    })

webdjango/templates/Register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
     <link href="{%static 'shop/css/login.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	{% if error %}
<h4 style="color:red">{{ error }}</h4>
{% endif %}

	<img class="wave" src="{%static 'shop/images/wave.png' %}">
	<div class="container">
		<div class="img">
			{% if error %}
<h4 style="color:red">{{ error }}</h4>
{% endif %}

		</div>
		<div class="login-content">
 <form method="POST" >
         {% csrf_token %}
				<img src="{%static 'shop/images/avatar.svg' %}">
				<h2 class="title">Create an account</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Username</h5>
           		   		<input type="text" name="username" class="input" />
                       </div>
                    </div>
     <div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-email"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Email</h5>
           		   		 <input type="text" name="email" class="input" />
                       </div>
                    </div>
     <div class="input-div pass">
           		   <div class="i">
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Password</h5>
           		    	<input type="password" name="password" class="input" />
            	   </div>
            	</div>
     <div class="input-div pass">
           		   <div class="i">
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Re Password</h5>
           		    	  <input type="password" name="repeatpassword" class="input" />
            	   </div>
            	</div>
            	 <a href="/shop/login">Already an account Sign in</a>
            	<input type="submit" name="submit" class="btn" value="submit">
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{%static 'shop/js/main.js' %}"></script>
</body>
</html>

webdjango/templates/ShopCart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Books</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
    <td>{{ book.product }}</td>
    <td>{{ book.user }}</td>
    <td>{{ book.quantity }}</td>

    </tr>
    {% endfor %}
</tbody>
</table>



</body>
</html>

webdjango/templates/about.html
	 <h3>Categories</h3>


				 {% for c in categories %}
    <li {% if category.slug == c.slug %} {%endif %}>
        <a href ="{{ c.get_absolute_url }}">{{c.name}}</a>
        {{c.id}}
        {{c.slug}}
    </li>

	{% endfor %}

webdjango/templates/change-password.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

    <style>
        .progress-bar-warning {
            background-color: yellow;
        }

        .progress-bar-danger {
            background-color: red;
        }

        .progress-bar-success {
            background-color: green;
        }

        .errorlist li {
            color: red;
        }
        .helptext li {
            color: green;
        }
    </style>
<link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}

    <h1>Change {{ profile.first_name }} {{ profile.last_name }} Password</h1>
    <form role="form" method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" value="Save">
    </form>

{% endblock %}

webdjango/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<center><h1> {%if category %}{{ category.name}}{% else %}{% endif %}</h1></center>
<center><h1>{%if subcategory %}{{ subcategory.name}}{% else %}{% endif %}</h1></center>
{% for product in products %}
    <div class="container">

        <div class="gallery">
{% if product_list %}
{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
    </div>
</body>
{% endfor %}

{% endblock %}

webdjango/templates/recommend.html
{% extends 'base.html'%}
{% block title %}Recommendations{% endblock %}
{% block body %}

<div class="container-fluid">
	<h2>Recommendations for You </h2>
</div>


	<div class="container">
    
    <!-- Movie list -->
    <div class="gallery">
            {% if movie_list %}
            {% for movie in movie_list %}
                <div class="col-sm-2 col-md-2 ">
                    <div class="thumbnail">
                        <h4>{{movie.title}}</h4>
                        <a href="{% url 'shop:product_detail' product_id=movie.id %}">
                            <img src="{{ movie.image.url}}" class="img-responsive">
                        </a>
                        <h5>{{movie.genre}}</h5>
                        <div class="caption">

                            <!-- View Details -->
                            <a href="{% url 'shop:product_detail' product_id=movie.id %}" class="btn btn-primary btn-sm" role="button">Give Rating</a>

                                        
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
        </div>
    
</div>

{% endblock %}

webdjango/templates/recommendation.html
{% extends 'product_list.html' %}

{% block body %}
<h2 style="margin-top:40px;" class="text-center">Popularity based Recommendation</h2>
<div class="row">
{%for a in  object_list.itertuples %}
<div class="col-md-3">


    <div class="card-header"> Average rating: {{a.avg_rating}} | Total rating: {{ a.num_ratings }}  </div>
            <div class="card-body">
                  <div class="card-title"> Product name : {{a.name}}

</div>
        </div>
     <p class="card-text text_black"> {{a.description}}</p>

    </div>
<br>
    <br>

{% endfor %}
</div>

{% endblock %}

webdjango/templates/reviewsbase.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Winerama</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:wine_list' %}">Wine list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'reviews:user_recommendation_list' %}">Wine suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

webdjango/templates/shop_cart_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Shop Cart List{% endblock %}
{% block css %}
<link href="{%static 'shop/css/shoppingcart.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}

    <div class="wrap cf">
  <div class="heading cf">
    <h1>My Cart</h1>
    <a href="{% url 'shop:index' %}" class="continue">Continue Shopping</a>
  </div>
  <div class="cart">
    <ul class="cartWrap">
        {% for rs in shopcart %}
      <li class="items even">
    <div class="infoWrap">
        <div class="cartSection">
        <img src="{{rs.product.image.url}}" alt="" class="itemImg" />
          <p class="itemNumber">#QUE-007544-002</p>
          <h3>{{rs.product.name}}</h3>

           <p> <input type="text"  class="qty" placeholder="{{rs.quantity}}"/>  X <del>Rs.{{rs.product.price}}</del> Rs.{{ rs.product.discount_price }}</p>

        </div>

        <div class="prodTotal cartSection">
          <p class="stockStatus">= Rs. {{ rs.amount }}</p>
        </div>
              <div class="cartSection removeWrap">
           <a href="/order/deletefromcart/{{ rs.id }}" class="remove">x</a>
        </div>
      </div>
      </li>
        {% endfor %}


    </ul>
  </div>

  <div class="promoCode"><label for="promo">Have A Promo Code?</label><input type="text" name="promo" placholder="Enter Code" />
  <a href="#" class="btn"></a></div>

  <div class="subtotal cf">
    <ul>
      <li class="totalRow"><span class="label">Subtotal</span><span class="value">Rs. {{ carttotal }}</span></li>

          <li class="totalRow"><span class="label">Shipping</span><span class="value">Free Shipping</span></li>

            <li class="totalRow"><span class="label">Tax</span><span class="value">{{carttax}}</span></li>
            <li class="totalRow final"><span class="label">Total</span><span class="value">{{cartwithtax }}</span></li>
      <li class="totalRow"><a href="/order/checkout" class="btn continue">Checkout</a></li>
    </ul>
  </div>
</div>
{% endblock %}

webdjango/templates/shoplist.html
{% extends 'base.html' %}
{% load static %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<center><h1> {%if category %}{{ category.name}}{% else %}{% endif %}</h1></center>
<center><h1>{%if subcategory %}{{ subcategory.name}}{% else %}{% endif %}</h1></center>
{% for product in products %}
    <div class="container">

        <div class="gallery">
{% if product_list %}
{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
    </div>
</body>
{% endfor %}

{% endblock %}

webdjango/templates/wine_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ wine.name }}</h2>
<h5>{{ wine.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if wine.review_set.all %}
<div class="row">
    {% for review in wine.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' wine.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}